### ISSUE TITLE
Adding this component intermittently fails configuration checks

### ISSUE THREAD

**Issue by rohankapoorcom** [zvldz/ha_custom_filters#2]
Home Assistant version: 0.118.3
ha_custom_filters version: 3c805dee06f2ce6cdfde4036f186f562c4a657aa

I'm running into an odd problem with this component. It works fine during normal use, but occasionally trips up my [github actions based configuration checking run](https://github.com/rohankapoorcom/homeassistant-config/pull/33/checks?check_run_id=1490299855) with the following error:

```yaml
Failed config
  sensor.mqtt: 
    - Invalid config for [sensor.mqtt]: invalid template (TemplateAssertionError: no filter named 'decode_valetudo_map') for dictionary value @ data['json_attributes_template']. Got "{% if 'class' in value[1:10] %} {{ value }} {% else %} {{ value | decode_valetudo_map }} {% endif %}". (See ?, line ?). 
    - platform: mqtt
      json_attributes_template: {% if 'class' in value[1:10] %} {{ value }} {% else %} {{ value | decode_valetudo_map }} {% endif %}
      json_attributes_topic: valetudo/downstairs-rockrobo/map_data
      name: downstairs_roborock_map
      state_topic: valetudo/downstairs-rockrobo/state
      value_template: OK
    - Invalid config for [sensor.mqtt]: invalid template (TemplateAssertionError: no filter named 'decode_valetudo_map') for dictionary value @ data['json_attributes_template']. Got "{% if 'class' in value[1:10] %} {{ value }} {% else %} {{ value | decode_valetudo_map }} {% endif %}". (See ?, line ?). 
    - platform: mqtt
      json_attributes_template: {% if 'class' in value[1:10] %} {{ value }} {% else %} {{ value | decode_valetudo_map }} {% endif %}
      json_attributes_topic: valetudo/upstairs-rockrobo/map_data
      name: upstairs_roborock_map
      state_topic: valetudo/upstairs-rockrobo/state
      value_template: OK
```

My best guess is that this is because the custom filters component is likely not getting installed before the mqtt sensors are processed.

Any suggestions on resolving this?
